// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package inject

import (
	"OnlineDeck/entry/controller/decks"
	"OnlineDeck/pkg/dao"
	"OnlineDeck/pkg/services/deck"
)

// Injectors from wire.go:

func DeckController() *decks.Controller {
	deckDao := dao.NewDeckDao()
	service := deck.NewService(deckDao)
	controller := decks.NewDeckController(service)
	return controller
}
